// Generated by CoffeeScript 1.3.3
(function() {

  window.Karate = (function() {

    function Karate() {}

    Karate.prototype.chop = function(int, arr) {
      var max, min;
      min = 0;
      max = arr.length - 1;
      return this.binary_search(int, arr, min, max);
    };

    Karate.prototype.binary_search = function(int, arr, min, max) {
      var mid;
      mid = parseInt((min + max) / 2);
      if (arr[mid] === int) {
        return mid;
      } else {
        while (max > min) {
          if (arr[mid] < int) {
            min = mid + 1;
            return this.binary_search(int, arr, min, max);
          } else if (arr[mid] > int) {
            max = mid - 1;
            return this.binary_search(int, arr, min, max);
          }
        }
      }
      return -1;
    };

    return Karate;

  })();

}).call(this);
